
platform :osx, '10.9'

target 'MasonryDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MasonryDemo
  pod 'Masonry'
end
